[project]
name = "example"
version = "0.1.0"
description = "Mi ejemplo"
authors = [
    {name = "Fabián",email = "fabianibaro@nexgen.mx"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests (>=2.32.4,<3.0.0)",
    "flask (>=3.1.1,<4.0.0)",
    "rich (>=14.0.0,<15.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
